
export const contentOneDataEn = [ 
 {name : "Brihaspathi prescribed certain herbs to cure the wound on Lord Vishnu's head. While searching the hills for those herbs, lord Vishnu met Varaha Swami (the boar avatar of Lord Vishnu) and requested him for a place to stay till the end of Kali Yuga. Varaha Swami obliged Him on the condition that Lord Vishnu would pay the price for the land. He marked out the land and even sent Vakula Devi to look after Him. In return, Varaha Swami would receive the first prayer – puja and the offering of food – naivedyam, from Lord Vishnu's devotees."}, 
 {name : "Vakula Devi was the incarnation of Sri Krishna's mother, Yashoda. Yashoda was saddened by the fact that she was not blessed to witness the marriage of Sri Krishna with Rukmini. That is how she was privileged to be close to the Lord once agin a Vakula Devi"}, 
 {name : "The legend countinues . The cused Chola King (having paid his price as a demon) was reborn as Akasa Raja, the ruler of Tondamandalam. Although Akasa Raja had a brother Tondaman, he had no heirs. A decision was made to have a grand puja. Whilst ploughing the fields in its preparation a thousand petalled lotus was unearthed."},
 {name : "A beautiful infant girl cradled amoungst the lotus petals surprised and thrilled him. He carried the child to his palace and presented her to his Queen – Dharani Devi. They named their daughter Padmavati after the lotus that she was found in. Padmavati grew into a beautiful princess. Sage Narada, on one of him many visits to the palace enlightened Padmavati of her destiny – she would soon become the spouse of Lord Vishnu Himself."},
 {name : "The other half of the legend unfolds. Lord Vishnu whilst hunting in the forest surrounding the hills, pursues a wild elephannt. He enters the same garden as Princess Padmavati and her companions. When the Lord sees the enchanting princes, He falls in love with her."},
 {name : "Upon returning home, He confides in Vakula Devi. While narrating the day's experiences, He also tells her about His promise make to Vedavati in His previous birth as Rama. Lord Vishnu had promised to marry Vedavati in her next birth and now she was here as Padmavati."},
 {name : "In the Ramayanam when Ravana was about to cary away Sita in the absence of Rama and Lakshmana, Lord Agni appeared and offered Vedavati to Ravana as the real Sita. Ravana was tricked in to thinking that Vedavati was Sita while the real Sita stayed in Agni's house."},
 {name : "After Ravana's destruction Vedavati faces rejection from Rama. She then gives herself up to the sacrificial flames of the fire. Agni, then offers the real Sita to Rama. Rama is enlightened by Sita, regarding Vedavati's endurance of Ravana's torture for ten months in lanka. He then promises to wed Vadavati in her next birth when she would be reborn as a padmavati."},
 {name : "Lord Vishnu's proposal of marriage to the Princess Padmavati is yet another interesting pard of the legend. Vakula Devi offered to take the proposal to Akasa Raja on Lord Vishnu's behalf. However Lord Vishnu was anxious and doubtful as to whether Vakula Devi would return successful. So then, He assumed the form of a lady fortune-teller and informed Queen Dharani Devi that Princess padmavati would soon marry lady bearing the proposal on behalf of the Lord."},
 {name : "The events unfolded as planned and Akasa Raja requested the palace purohits to fix a mahurtam for the marriage Anxiety and concern about raising the substantial sum for the grand wedding ceremony led Vakula Devi and Lord Vishnu to seek the advice of Lord Brahma and Lord Shiva. They suggested Kubera's help in this regard. An agreement was reached wherein Kubera's loan to the Lord would be repaid with interest. In fact, it is believed that all the offerings in the hundi, to this day , form part of the repayment to Kubera"},
 {name : "The wedding ceremony was blessed with the presence of the Devas. Amongst the traditional festivities and rituals, the presentation of a diamond studded crown to Lord Vishnu by Akasa Raja enhanced the grandeur of the occasion furthermore. To this day the crown adorns the idol of Lord Venkateswara Swami in Tirumala."},
]

export const contentTwoDataEn = [ 
 {name : 'Naradha needed some help to accomplish his mission. He then went to the banks of the River Ganga, where several sages were performing a yagna. The sages could not decide as to who was worthy of the fruit of their yagna. Sage Bhrigu decided to solve the problem by examinig the Hindu trinity -Lord Brahma the creator , Lord vishnu the protector and Lord Shiva the destroyer.'}, 
 {name : "Sage Bhrigu visited satyalokam, the abode of Lord Brahma. Infuriated by his indifferent behaviour, sage Bhrigu cursed Him saying that He would have no shrine on earth to dwell in. When Lord Brahma was creating the universe, one of His creations was Shatarupa (a female deity with a hundred beautiful forms). Her beauty was such that lord Brahma Himself was infatuated by her. Shatarupa tried to avoid Lord Brahma's gaze by moving away but she did not succeed as Lord Brahma developed five heads, and Hid gaze, followed her wherever she went. "}, 
 {name : "Lord shiva decided that it was wrong of Lord Brahma to be obsessed with her as having created her, she was like a daughter to Him. Lord Shiva cut off Lord Brahma's uppermost head and directed that there be no proper worship fo the 'Unholy' Lord . From that time on, Lord Brahma took to reciting the four Vedas – each of His four heads representing a Veda. Sage Bhrigu then visited Lord Shiva's abode – Kailasam. Lord Shiva was absorbed in the Kailasam. "}, 
 {name : "Lord Shiva was absorbed in the company of His consort- Parvati Devi, and was quite indigant at Sage Bhrigu's interruption. Sage Bhrigu cursed Lord Shiva by saying that He would be worshipped on earth, only in the form of a Lingam. Finally, when Sage Bhrigu reached Vaikuntam, the abode of the Lord Vishnu, he found the Lord reclining on Adisesha completely engrossed with His consort, Goddess Mahalakshmi, enraged at being ignored, sage Bhrigu kicked Lord Vishnu on His chest."},
 {name : "Lord Vishnu immediately got up and apologised to Sage Bhrigu for His behaviour. As He massaged his foot in apology. He removed the Sage's third eye, that gave him the power to defy the Devas. Pleased by Lord Vishnu's act, Sage Bhrigu decided that the yagna was to be dedicated to Lord Vishnu."},
 {name : "In the meantime, Goddess mahalakshmi, who felt humiliated and angry towards Sage Bhrigu for having kicked her husband, departed from Vaikuntam and made her way to Karavirapura (now Kolhapur in the state of Maharashtra) where she performed penance and meditation. Unable to bear the loneliness caused by the separation , the Lod made His way to earth in search of Goddess Mahalakshmi, but in vain. Tired after searching endlessly, the Lord reached Tirumala and entered the ant-hill beneath the tamarind tree on the southern bank of Swami pushkarini. He lived there for thousands of years."},
 {name : "It is in the reign of a Chola King that the story unfolds futher. Goddess Mahalakshmi who still lived in Karavirapura knew instinctively that Her Lord had left Vaikuntam and was living in an ant-hill in Tirumala. Regretting having left Him, Goddess Mahalakshmi in the form of a cowhedess sold Lord Brahma in the form of a cow and Lord Shiva in the form of a calf to the Chola Queen. Lord Brahma and Lord Shiva took these forms to look after Lord Vishnu so that Goddess Mahalakhmi would no longer need to worry about His well-being."},
 {name : "Everyday the cow and the calf accompanied the Chola King's herd of two thousand cattle to graze on the hillside. Unnoticed, the cow would empty its milk on the ant hill. For Lord Vishnu to drink. When the Chola Queen found out that the cow was not yielding any milk, she took the cowherd to task."},
 {name : "The next day the cowherd followed the cow to the ant-hill and watched as it emptied its milk there. The cowherd's anger knew no bounds. He was furious and threw his axe at the cow, but Lord Vishnu took the blow and saved the cow."},
 {name : "Shocked at what he had done, the cowherd fainted. The cow immediately ran to the place and returned to the scene of the incident along with the King. The King was punished for the act of his cowherd by Lord Vishnu. He was cursed to be a demon. The King prayed for mercy and Lord Vishnu softened and told him that he would have to suffer the curse, but then would be reborn as Akasa Raja, whose daughter Padmavati would be married to the Lord Himself. The cowherd was rewarded with the boon that his descendents (Yadavas ) would have the first glimpse of the Lord everyday in Tirumala."},
]

export const contentOneDataTn = [
    {name : "விஷ்ணுவின் தலையில் ஏற்பட்ட காயத்தை குணப்படுத்த பிருஹஸ்பதி சில மூலிகைகளை பரிந்துரைத்தார். அந்த மூலிகைகளை மலைகளில் தேடும் போது, ​​விஷ்ணு வராஹ ஸ்வாமியை (விஷ்ணுவின் பன்றி அவதாரம்) சந்தித்து, இறுதி வரை தங்குவதற்கு இடம் கேட்டார். வராஹ ஸ்வாமி, அந்த நிலத்திற்கான விலையைக் கொடுக்க வேண்டும் என்ற நிபந்தனையின் பேரில், வராஹ ஸ்வாமி அவரைப் பார்த்துக் கொள்ளும்படி அனுப்பினார் அன்னதானம் - நைவேத்யம், விஷ்ணுவின் பக்தர்களிடமிருந்து."},
    {name : "வகுளா தேவி ஸ்ரீ கிருஷ்ணரின் தாயான யசோதாவின் அவதாரம். ருக்மிணியுடன் ஸ்ரீ கிருஷ்ணரின் திருமணத்தைக் காணும் பாக்கியம் தனக்கு கிடைக்கவில்லையே என்று யசோதா வருத்தப்பட்டார். அப்படித்தான் ஒருமுறை இறைவனுடன் நெருங்கிப் பழகும் பாக்கியம் கிடைத்தது. ஆகின் வகுலா தேவி"},
    {name : "The legend countinues . பழிவாங்கப்பட்ட சோழ மன்னன் (அரக்கனாக விலை கொடுத்து) தொண்டமண்டலத்தை ஆண்ட ஆகாச ராஜாவாக மீண்டும் பிறந்தான். ஆகாச ராஜாவுக்கு ஒரு சகோதரன் தொண்டமான் இருந்தபோதிலும், அவனுக்கு வாரிசுகள் இல்லை. ஒரு முடிவு எடுக்கப்பட்டது. வயலை உழும் போது ஆயிரம் இதழ்கள் கொண்ட தாமரை வெளிப்பட்டது."},
    {name : "தாமரை இதழ்களின் நடுவே ஒரு அழகான பெண் குழந்தைத் தொட்டிலில் அமர்ந்து அவரை ஆச்சரியப்படுத்தியது மற்றும் பரவசப்படுத்தியது. அவர் குழந்தையைத் தன் அரண்மனைக்கு அழைத்துச் சென்று தனது ராணி - தரணி தேவியிடம் ஒப்படைத்தார். அவர்கள் தங்கள் மகளுக்கு பத்மாவதி என்று பெயரிட்டனர். அவள் கிடைத்த தாமரைக்கு பத்மாவதி. நாரத முனிவர் ஒரு அழகான இளவரசியாக வளர்ந்தார், அவர்களில் ஒருவரான பத்மாவதி அரண்மனைக்கு வருகை தந்தார் - அவள் விரைவில் விஷ்ணுவின் மனைவியாக மாறுவாள்."},
    {name : "புராணத்தின் மற்ற பாதி விரிவடைகிறது. மலைகளைச் சுற்றியுள்ள காட்டில் வேட்டையாடும் போது, ​​ஒரு காட்டு யானையைப் பின்தொடர்ந்தார். அவர் அதே தோட்டத்தில் இளவரசி பத்மாவதி மற்றும் அவரது தோழர்களுடன் நுழைகிறார். இறைவன் மயக்கும் இளவரசர்களைக் கண்டதும், அவர் விழுகிறார். அவளை காதலிக்கிறேன்."},
    {name : "வீடு திரும்பியதும், அவர் வகுளா தேவியிடம் கூறுகிறார். அன்றைய அனுபவங்களைச் சொல்லும் போது, ​​அவர் தனது முந்தைய பிறவியில் ராமனாக வேதவதிக்கு அளித்த வாக்குறுதியைப் பற்றியும் கூறுகிறார். விஷ்ணு, வேதவதியை அடுத்த பிறவியில் திருமணம் செய்து கொள்வதாக உறுதியளித்தார். அவள் பத்மாவதியாக இங்கே இருந்தாள்."},
    {name : "ராமாயணத்தில் ராமர் மற்றும் லட்சுமணன் இல்லாத நேரத்தில் ராவணன் சீதையை தூக்கிச் செல்ல இருந்தபோது, ​​​​அக்னி பகவான் தோன்றி ராவணனுக்கு வேதவதியை உண்மையான சீதையாக வழங்கினார். ராவணன் வேதவதியை சீதை என்று நினைத்து ஏமாற்றினார். அக்னியின் வீட்டில் தங்கினார்."},
    {name : "ராவணனின் அழிவுக்குப் பிறகு வேதவதி ராமனிடமிருந்து நிராகரிப்பை எதிர்கொள்கிறாள். பின்னர் அவள் நெருப்பின் தியாகச் சுடருக்குத் தன்னைக் கொடுக்கிறாள். அக்னி, பின்னர் ராமருக்கு உண்மையான சீதையை வழங்குகிறாள். ராவணனின் சித்திரவதைகளை வேதவதியின் சகிப்புத்தன்மை குறித்து ராமருக்கு சீதையால் ஞானம் ஏற்படுகிறது. இலங்கையில் பல மாதங்கள் வாதாவதியை அடுத்த பிறவியில் திருமணம் செய்து கொள்வதாக உறுதியளித்தார்."},
    {name : "இளவரசி பத்மாவதிக்கு விஷ்ணுவின் திருமண முன்மொழிவு புராணத்தின் மற்றொரு சுவாரஸ்யமான பகுதியாகும். வகுலா தேவி விஷ்ணுவின் சார்பாக ஆகாச ராஜாவிடம் முன்மொழிந்தார். இருப்பினும், வகுலா தேவி வருவாளா என்று விஷ்ணு ஆர்வமாகவும் சந்தேகமாகவும் இருந்தார். பின்னர் வெற்றிகரமாக திரும்பி வர, அவர் ஒரு பெண் ஜோதிட வடிவத்தை எடுத்து, இளவரசி பத்மாவதி விரைவில் இறைவனின் சார்பாக திருமணம் செய்து கொள்வார் என்று ராணி தரணி தேவிக்குத் தெரிவித்தார்."},
    {name : "திட்டமிட்டபடி நிகழ்வுகள் நடந்தன, ஆகாச ராஜா அரண்மனை புரோகிதர்களிடம் திருமணத்திற்கு ஒரு மஹூர்தம் நிர்ணயம் செய்யுமாறு கேட்டுக் கொண்டார் இது சம்பந்தமாக குபேரனின் உதவியை சிவபெருமான் பரிந்துரைத்தார். குபேரனுக்கு"},
    {name : "திருமண விழாவில் தேவர்கள் முன்னிலையில் ஆசீர்வதிக்கப்பட்டது. பாரம்பரிய விழாக்கள் மற்றும் சடங்குகளுக்கு மத்தியில், ஆகாச ராஜா விஷ்ணுவுக்கு வைரம் பதித்த கிரீடத்தை சமர்ப்பித்தது விழாவின் சிறப்பை மேலும் மேம்படுத்தியது. இன்று வரை கிரீடம் அலங்கரிக்கிறது. திருமலையில் உள்ள வெங்கடேஸ்வர சுவாமி சிலை."},
   ]

export const contentTwoDataTn = [
    {name : "விஷ்ணுவின் தலையில் ஏற்பட்ட காயத்தை குணப்படுத்த பிருஹஸ்பதி சில மூலிகைகளை பரிந்துரைத்தார். அந்த மூலிகைகளை மலைகளில் தேடும் போது, ​​விஷ்ணு வராஹ ஸ்வாமியை (விஷ்ணுவின் பன்றி அவதாரம்) சந்தித்து, இறுதி வரை தங்குவதற்கு இடம் கேட்டார். வராஹ ஸ்வாமி, அந்த நிலத்திற்கான விலையைக் கொடுக்க வேண்டும் என்ற நிபந்தனையின் பேரில், வராஹ ஸ்வாமி அவரைப் பார்த்துக் கொள்ளும்படி அனுப்பினார் அன்னதானம் - நைவேத்யம், விஷ்ணுவின் பக்தர்களிடமிருந்து."},
    {name : "வகுளா தேவி ஸ்ரீ கிருஷ்ணரின் தாயான யசோதாவின் அவதாரம். ருக்மிணியுடன் ஸ்ரீ கிருஷ்ணரின் திருமணத்தைக் காணும் பாக்கியம் தனக்கு கிடைக்கவில்லையே என்று யசோதா வருத்தப்பட்டார். அப்படித்தான் ஒருமுறை இறைவனுடன் நெருங்கிப் பழகும் பாக்கியம் கிடைத்தது. ஆகின் வகுலா தேவி"},
    {name : "The legend countinues . பழிவாங்கப்பட்ட சோழ மன்னன் (அரக்கனாக விலை கொடுத்து) தொண்டமண்டலத்தை ஆண்ட ஆகாச ராஜாவாக மீண்டும் பிறந்தான். ஆகாச ராஜாவுக்கு ஒரு சகோதரன் தொண்டமான் இருந்தபோதிலும், அவனுக்கு வாரிசுகள் இல்லை. ஒரு முடிவு எடுக்கப்பட்டது. வயலை உழும் போது ஆயிரம் இதழ்கள் கொண்ட தாமரை வெளிப்பட்டது."},
    {name : "தாமரை இதழ்களின் நடுவே ஒரு அழகான பெண் குழந்தைத் தொட்டிலில் அமர்ந்து அவரை ஆச்சரியப்படுத்தியது மற்றும் பரவசப்படுத்தியது. அவர் குழந்தையைத் தன் அரண்மனைக்கு அழைத்துச் சென்று தனது ராணி - தரணி தேவியிடம் ஒப்படைத்தார். அவர்கள் தங்கள் மகளுக்கு பத்மாவதி என்று பெயரிட்டனர். அவள் கிடைத்த தாமரைக்கு பத்மாவதி. நாரத முனிவர் ஒரு அழகான இளவரசியாக வளர்ந்தார், அவர்களில் ஒருவரான பத்மாவதி அரண்மனைக்கு வருகை தந்தார் - அவள் விரைவில் விஷ்ணுவின் மனைவியாக மாறுவாள்."},
    {name : "புராணத்தின் மற்ற பாதி விரிவடைகிறது. மலைகளைச் சுற்றியுள்ள காட்டில் வேட்டையாடும் போது, ​​ஒரு காட்டு யானையைப் பின்தொடர்ந்தார். அவர் அதே தோட்டத்தில் இளவரசி பத்மாவதி மற்றும் அவரது தோழர்களுடன் நுழைகிறார். இறைவன் மயக்கும் இளவரசர்களைக் கண்டதும், அவர் விழுகிறார். அவளை காதலிக்கிறேன்."},
    {name : "வீடு திரும்பியதும், அவர் வகுளா தேவியிடம் கூறுகிறார். அன்றைய அனுபவங்களைச் சொல்லும் போது, ​​அவர் தனது முந்தைய பிறவியில் ராமனாக வேதவதிக்கு அளித்த வாக்குறுதியைப் பற்றியும் கூறுகிறார். விஷ்ணு, வேதவதியை அடுத்த பிறவியில் திருமணம் செய்து கொள்வதாக உறுதியளித்தார். அவள் பத்மாவதியாக இங்கே இருந்தாள்."},
    {name : "ராமாயணத்தில் ராமர் மற்றும் லட்சுமணன் இல்லாத நேரத்தில் ராவணன் சீதையை தூக்கிச் செல்ல இருந்தபோது, ​​​​அக்னி பகவான் தோன்றி ராவணனுக்கு வேதவதியை உண்மையான சீதையாக வழங்கினார். ராவணன் வேதவதியை சீதை என்று நினைத்து ஏமாற்றினார். அக்னியின் வீட்டில் தங்கினார்."},
    {name : "ராவணனின் அழிவுக்குப் பிறகு வேதவதி ராமனிடமிருந்து நிராகரிப்பை எதிர்கொள்கிறாள். பின்னர் அவள் நெருப்பின் தியாகச் சுடருக்குத் தன்னைக் கொடுக்கிறாள். அக்னி, பின்னர் ராமருக்கு உண்மையான சீதையை வழங்குகிறாள். ராவணனின் சித்திரவதைகளை வேதவதியின் சகிப்புத்தன்மை குறித்து ராமருக்கு சீதையால் ஞானம் ஏற்படுகிறது. இலங்கையில் பல மாதங்கள் வாதாவதியை அடுத்த பிறவியில் திருமணம் செய்து கொள்வதாக உறுதியளித்தார்."},
    {name : "இளவரசி பத்மாவதிக்கு விஷ்ணுவின் திருமண முன்மொழிவு புராணத்தின் மற்றொரு சுவாரஸ்யமான பகுதியாகும். வகுலா தேவி விஷ்ணுவின் சார்பாக ஆகாச ராஜாவிடம் முன்மொழிந்தார். இருப்பினும், வகுலா தேவி வருவாளா என்று விஷ்ணு ஆர்வமாகவும் சந்தேகமாகவும் இருந்தார். பின்னர் வெற்றிகரமாக திரும்பி வர, அவர் ஒரு பெண் ஜோதிட வடிவத்தை எடுத்து, இளவரசி பத்மாவதி விரைவில் இறைவனின் சார்பாக திருமணம் செய்து கொள்வார் என்று ராணி தரணி தேவிக்குத் தெரிவித்தார்."},
    {name : "திட்டமிட்டபடி நிகழ்வுகள் நடந்தன, ஆகாச ராஜா அரண்மனை புரோகிதர்களிடம் திருமணத்திற்கு ஒரு மஹூர்தம் நிர்ணயம் செய்யுமாறு கேட்டுக் கொண்டார் இது சம்பந்தமாக குபேரனின் உதவியை சிவபெருமான் பரிந்துரைத்தார். குபேரனுக்கு"},
    {name : "திருமண விழாவில் தேவர்கள் முன்னிலையில் ஆசீர்வதிக்கப்பட்டது. பாரம்பரிய விழாக்கள் மற்றும் சடங்குகளுக்கு மத்தியில், ஆகாச ராஜா விஷ்ணுவுக்கு வைரம் பதித்த கிரீடத்தை சமர்ப்பித்தது விழாவின் சிறப்பை மேலும் மேம்படுத்தியது. இன்று வரை கிரீடம் அலங்கரிக்கிறது. திருமலையில் உள்ள வெங்கடேஸ்வர சுவாமி சிலை."},
   ]